# PostgreSQL configuration example
production:
  adapter: postgresql
  database: postgresdb_prod
  host: localhost
  username: postgres
  password: "lidenise"

development:
  adapter: postgresql
  database: postgresdb_dev
  host: localhost
  username: postgres
  password: "lidenise"

test:
  adapter: postgresql
  database: postgresdb_test
  host: localhost
  username: postgres
  password: "lidenise"
